project:
  type: website

website:
  title: "IASC-ARS 2023"
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - keynote.qmd
      - program.qmd
      - venue.qmd
      - conduct.qmd
      - contact.qmd

format:
  html:
    theme:
      light: cerulean
      dark: darkly
    css: styles.css
    toc: true



