---
title: "Code of Conduct"
---

IASC-ARS 2023 at Macquarie University is committed to providing a welcoming and harassment-free experience for everyone, regardless of gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion (or lack thereof), or technology choices. We do not tolerate harassment of participants in any form. Sexual language and imagery is not appropriate for any event venue, including talks, workshops, social activities, social media, and other online media. Participants violating these rules may be sanctioned or expelled from the event at the discretion of the conference organisers.

This code of conduct applies to all participants, helpers and sponsors and applies to all modes of interaction, both in-person and online.

Participants of IASC-ARS 2023 agree to:

- **Respectful Behaviour**: All attendees are expected to be respectful and considerate towards one another at all times. Harassment or discriminatory behaviour, including but not limited to verbal abuse, physical intimidation, or offensive language will not be tolerated.
- **Inclusive Environment**: We will strive to create an inclusive and diverse environment that welcomes all attendees, including those with disabilities, and promotes equal opportunities for all.
- **Professionalism**: Attendees will conduct themselves in a professional and courteous manner at all times, whether it be during conference sessions, social events, or online interactions. Attendees are expected to adhere to the conference agenda and respect the speaker's allotted time.
- **Privacy**: Attendees will respect each other's privacy and personal information, and will not share or use this information inappropriately.
- **Reporting**: Any incidents of harassment or discrimination should be reported to a member of the Response Team (names and contact details will be made available before the conference) immediately. The response team will handle all reports with sensitivity and confidentiality.

By following this code of conduct, we can all create a positive and productive atmosphere for all attendees to learn, collaborate, and share their knowledge and experiences.